# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '子窗口.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_child(object):
    def setupUi(self, child):
        child.setObjectName("child")
        child.resize(461, 460)
        self.centralwidget = QtWidgets.QWidget(child)
        self.centralwidget.setObjectName("centralwidget")
        child.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(child)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 26))
        self.menubar.setObjectName("menubar")
        child.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(child)
        self.statusbar.setObjectName("statusbar")
        child.setStatusBar(self.statusbar)

        self.retranslateUi(child)
        QtCore.QMetaObject.connectSlotsByName(child)

    def retranslateUi(self, child):
        _translate = QtCore.QCoreApplication.translate
        child.setWindowTitle(_translate("child", "子窗口"))
