# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '子窗口2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_child2(object):
    def setupUi(self, child2):
        child2.setObjectName("child2")
        child2.resize(424, 463)
        self.centralwidget = QtWidgets.QWidget(child2)
        self.centralwidget.setObjectName("centralwidget")
        child2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(child2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 26))
        self.menubar.setObjectName("menubar")
        child2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(child2)
        self.statusbar.setObjectName("statusbar")
        child2.setStatusBar(self.statusbar)

        self.retranslateUi(child2)
        QtCore.QMetaObject.connectSlotsByName(child2)

    def retranslateUi(self, child2):
        _translate = QtCore.QCoreApplication.translate
        child2.setWindowTitle(_translate("child2", "子窗口2"))
